name: Checkov
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/eks-cluster
          framework: terraform
          skip_checks: CKV_AWS_20,CKV_AWS_145,CKV_AWS_355,CKV_AWS_290,CKV_AWS_289,CKV_AWS_287,CKV_AWS_40